// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace M007_EFCore_DBFirst.Models;

public partial class KursDBContext : DbContext
{
    public KursDBContext() { }

    public KursDBContext(DbContextOptions<KursDBContext> options) : base(options) { }

    public virtual DbSet<KursInhalte> KursInhaltes { get; set; }

    public virtual DbSet<Kurse> Kurses { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		=> optionsBuilder.UseSqlServer("Data Source=localhost;Initial Catalog=KursDB;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<KursInhalte>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__KursInha__3214EC2792AD7B25");

            entity.HasOne(d => d.Kurs).WithMany(p => p.KursInhaltes).HasConstraintName("FK_KursID");
        });

        modelBuilder.Entity<Kurse>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Kurse__3214EC27A6E3F9C0");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}