// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace M007_EFCore_DBFirst.Models;

[Table("KursInhalte")]
public partial class KursInhalte
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("KursID")]
    public int? KursId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string InhaltTitel { get; set; }

    [ForeignKey("KursId")]
    [InverseProperty("KursInhaltes")]
    public virtual Kurse Kurs { get; set; }
}