// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace M007_DBAccess;

[Table("Personen")]
public partial class Personen
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Vorname { get; set; }

    [Required]
    public string Nachname { get; set; }

    public int Alter { get; set; }
}